### ISSUE TITLE
Information on chemscore

### ISSUE THREAD

**Issue by ajayarunachalam** [OpenAgInitiative/flavor-data#3]
Hi,

Can you elaborate more on this?

Thanks in advance

**Comment by srmoore** [comment]
This data is part of the paper published here:
https://doi.org/10.1371/journal.pone.0213918

The chemscore is talked about in section 2.2.6 as measurements of 17 different chemicals found in the GC-MS data. This experiment was done before my time with Open Ag, but I'll see if I can find information on which 17 chemicals were selected.

**Comment by ajayarunachalam** [comment]
@srmoore @ariellejohnson : Dear Researchers & Experts, 
Can i know which 17 chemicals were selected from your GC-MS data? Also, I have a very basic general doubt that can we claim that a bunch of particular chemicals are responsible for flavor in different plant species of study.

**Comment by srmoore** [comment]
I have yet to find out which 17 were chosen for the experiment (I'm doing another deep dive into the archives here today though... maybe I'll find them.) 

As for your second comment there, these 17 were chosen for this particular experiment with basil, not as a general purpose chemscore for flavor. Remember that the paper that this is associated with is a 'method' paper, showing the general process of selecting growing conditions can be used to optimize for selected chemical production in plants, not claiming to have come up with a standardized chemscore for flavor.

I'll update this issue again once I've either found something or have exhausted my search.

**Comment by srmoore** [comment]
I have part of an answer (I'm waiting to see if I can get the list of the full names of the compounds...)
All 36 chemicals identified in the GC-MS data are the 17 compounds. You'll see some things like replicated chemicals like alpha-cadinene and delta-cadinene that are difference configurations of the chemical and I believe other compounds breakdown into multiple chemicals in the mass spec. Again, I'm not an expert on how mass spec works. This is all due to the nature of how GC-MS works. 

The Chemscore for a grow/experiment is the average of the normalized abundance of each chemical from that experiment. To normalize each chemical you dived it by the standard deviation of that chemical across all experimental runs.

I hope this helps. I'll update again if I get any more information as many of the people involved with this paper have moved on from Open Ag.

I do know however that all the compounds that were chosen are know to influence flavor or aroma (which plays a large role in flavor). There is a whole discipline of science that deals with flavor and the compounds that make up flavor, and we had members on the team that came from that field.

**Comment by ajayarunachalam** [comment]
Okay. Thanks for the reply.

**Comment by ajayarunachalam** [comment]
@srmoore @ariellejohnson 
Any updates on the 17 compounds that were chosen mentioned in the article?

**Comment by srmoore** [comment]
I have tried reaching out to Arielle via other channels and have not received any word back.
Again, all the 17 compounds (and only those 17 compounds) are represented in the GCMS data, I just can't back out of that data the names of the flavor compounds for you. I'm going to close this comment for now.

**Comment by ajayarunachalam** [comment]
@srmoore : Okay fine. Thanks for all the efforts.
